# Exp ID
exp_id: default
infer_options: [
  "offline_all",
]

# thresholding
thresholding: q95.0

# Data Preprocessing
dataset: SWaT
batch_size: 64
eval_batch_size: 1
window_size: 12
stride: 12
eval_stride: 12
scaler: std

# test-time Hyperparameters
ttlr: 1e-03
normalization: "None"
gamma: 0.99

# Saving Configs & Paths
log_freq: 10
checkpoint_path: ./checkpoints
log_path: ./logs
output_path: ./outputs
plot_path: ./plots
result_path: ./results
plot_anomaly_scores: True
plot_recon_status: False
save_result: True
load_anoscs: True

# Model-specific arguments
defaults:
  - model: MLP