# Exp ID
exp_id: default
infer_options: [
  "offline_all",
  #"online_ST"
]

# offline range
qStart: 0.90
qEnd: 1.00
qStep: 0.01

# Data Preprocessing
dataset: NeurIPS-TS-MUL
batch_size: 64
eval_batch_size: 1
window_size: 12
stride: 1
eval_stride: 12
scaler: std
load_previous_error: True

# Training Hyperparameters
lr: 1e-03
epochs: 30

# test-time Hyperparameters
TT_loss: bce
cls_lambda: 1
ttlr: 1e-03
thlr: 1e-03

# normalization
normalization: "None"
gamma: 0.99

# Saving Configs & Paths
log_freq: 10
checkpoint_path: ./checkpoints
log_path: ./logs
output_path: ./outputs
plot_path: ./plots
result_path: ./results
plot_anomaly_scores: True
plot_recon_status: False

# Model-specific arguments
defaults:
  - model: MLP